### ISSUE TITLE
passwd: Segmentation fault on long passwords

### ISSUE THREAD

**Issue by runxiyu** [shadow-maint/shadow#1161]
`/usr/bin/passwd` provided by `community/shadow` segfaults when it receives a password longer than 256 characters, on Alpine Linux 3.21.0 on x86_64. I originally [reported it to Alpine](https://gitlab.alpinelinux.org/alpine/aports/-/issues/16784) but we think this is relevant upstream. Reproduced by quinq on the Alpine Linux IRC channel.

As far as I know there is nothing specific about Alpine's build process that could cause this; but I also could not reproduce this on Debian or Fedora.

Some Valgrind logs:

```
lindosaur:~# valgrind /tmp/passwd runxiyu # because setuid stuff
...
New password: 
Retype new password: 
==3604== 
==3604== Process terminating with default action of signal 11 (SIGSEGV)
==3604==  Bad permissions for mapped region at address 0x40A0220
==3604==    at 0x48D9685: explicit_bzero (in /usr/lib/libbsd.so.0.12.2)
==3604==    by 0x4CFA4FB: pam_sm_chauthtok (in /usr/lib/security/pam_unix.so)
==3604==    by 0x48C7159: ??? (in /usr/lib/libpam.so.0.85.1)
==3604==    by 0x48C7D83: pam_chauthtok (in /usr/lib/libpam.so.0.85.1)
==3604==    by 0x10D9A8: ??? (in /tmp/passwd)
==3604==    by 0x10B6AA: ??? (in /tmp/passwd)
==3604==    by 0x4041495: libc_start_main_stage2 (__libc_start_main.c:95)
==3604==    by 0x10B9C3: ??? (in /tmp/passwd)
==3604==    by 0x1: ???
==3604==    by 0x1FFF000DDE: ???
==3604==    by 0x1FFF000DEA: ???
...
Segmentation fault
```

Compiled with `CFLAGS='-ggdb3'`, then GDB:

```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7f33685 in explicit_bzero () from /usr/lib/libbsd.so.0
(gdb) bt
#0  0x00007ffff7f33685 in explicit_bzero () from /usr/lib/libbsd.so.0
#1  0x00007ffff7f194fc in pam_sm_chauthtok () from /usr/lib/security/pam_unix.so
#2  0x00007ffff7f4b15a in ?? () from /usr/lib/libpam.so.0
#3  0x00007ffff7f4bd84 in pam_chauthtok () from /usr/lib/libpam.so.0
#4  0x000055555555c9b3 in do_pam_passwd (user=0x7fffffffeddb "runxiyu", silent=false, change_expired=false) at pam_pass.c:46
#5  0x000055555555a9bd in main (argc=2, argv=0x7fffffffeb38) at passwd.c:1087
```

A brief investigation (credits Test_User for a lot of the work) seems to find nothing suspicious in shadow, however I'm not sure how to work with the PAM codebase so I'm reporting it here first.

Please tell me if I should report this to PAM instead. Thanks!

**Comment by runxiyu** [comment]
This bug is from how PAM interacts with musl libc, not shadow. Closing

**Comment by alejandro-colomar** [comment]
I'll reopen.  Please update us about the PAM issue.  I think it would be good to know what they do.  If PAM is somehow limited to 256 bytes. maybe we should limit ourselves to that too.

**Comment by alejandro-colomar** [comment]
Cc: @ldv-alt

**Comment by ldv-alt** [comment]
I suppose this was addressed by the side effect of https://github.com/linux-pam/linux-pam/pull/868.

**Comment by alejandro-colomar** [comment]
Thanks!  So, nothing to do here, right?

**Comment by ldv-alt** [comment]
Ideally, I'd like to have a feedback from the reporter confirming that the issue is indeed fixed.
Anyway, there is nothing to do on the side of passwd.

**Comment by runxiyu** [comment]
The issue seems to be that PAM on musl libc is limited to 256 bytes because of musl's CHAR_MAX. The segfault occurred because musl's crypt(3) returns a "*" (as a string literal, from a read-only region) on failure, and PAM attempts to clear it (probably because PAM likes to prevent secret data from staying in memory).
As far as I can see, it doesn't occur on normal configurations of glibc.
https://github.com/linux-pam/linux-pam/issues/866

**Comment by runxiyu** [comment]
Sorry, I was a bit tired and forgot
