### ISSUE TITLE
Unable to build documentation for 4.14.0-rc3(?)

### ISSUE THREAD

**Issue by ikerexxe** [shadow-maint/shadow#781]
After including the patch from https://github.com/shadow-maint/shadow/pull/780 I generated a new tarball following the instruction from https://github.com/shadow-maint/shadow/pull/777, and I face several problems when building the man pages (log below). This is the first time that I generate the tarball so that might be the problem. I've been checking the problem and I don't know what's happening, so any help would be much appreciated.

```
make[3]: Entering directory '/home/ipedrosa/fedpkg/shadow-utils/shadow-4.14.0/man/da'
if grep -q SHADOW-CONFIG-HERE ../groupdel.8.xml ; then \
    sed -e 's/^<!-- SHADOW-CONFIG-HERE -->/<!ENTITY % config SYSTEM "config.xml">%config;/' ../groupdel.8.xml > groupdel.8.xml; \
else \
    sed -e 's/^\(<!DOCTYPE .*docbookx.dtd"\)>/\1 [<!ENTITY % config SYSTEM "config.xml">%config;]>/' ../groupdel.8.xml > groupdel.8.xml; \
fi
itstool -i ../its.rules -d -l da -m messages.mo -o . groupdel.8.xml
Traceback (most recent call last):
  File "/usr/bin/itstool", line 1645, in <module>
    doc.apply_its_file(itsfile, userparams=userparams)
  File "/usr/bin/itstool", line 789, in apply_its_file
    doc = libxml2.parseFile(filename)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/libxml2.py", line 1362, in parseFile
    if ret is None:raise parserError('xmlParseFile() failed')
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
libxml2.parserError: xmlParseFile() failed
make[3]: *** [Makefile:706: groupdel.8.xml] Error 1
make[3]: Leaving directory '/home/ipedrosa/fedpkg/shadow-utils/shadow-4.14.0/man/da'
make[3]: *** Waiting for unfinished jobs....
make[3]: Entering directory '/home/ipedrosa/fedpkg/shadow-utils/shadow-4.14.0/man/da'
if grep -q SHADOW-CONFIG-HERE ../chfn.1.xml ; then \
    sed -e 's/^<!-- SHADOW-CONFIG-HERE -->/<!ENTITY % config SYSTEM "config.xml">%config;/' ../chfn.1.xml > chfn.1.xml; \
else \
    sed -e 's/^\(<!DOCTYPE .*docbookx.dtd"\)>/\1 [<!ENTITY % config SYSTEM "config.xml">%config;]>/' ../chfn.1.xml > chfn.1.xml; \
fi
itstool -i ../its.rules -d -l da -m messages.mo -o . chfn.1.xml
Traceback (most recent call last):
  File "/usr/bin/itstool", line 1645, in <module>
    doc.apply_its_file(itsfile, userparams=userparams)
  File "/usr/bin/itstool", line 789, in apply_its_file
    doc = libxml2.parseFile(filename)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/libxml2.py", line 1362, in parseFile
    if ret is None:raise parserError('xmlParseFile() failed')
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
libxml2.parserError: xmlParseFile() failed
make[3]: *** [Makefile:706: chfn.1.xml] Error 1
make[3]: Leaving directory '/home/ipedrosa/fedpkg/shadow-utils/shadow-4.14.0/man/da'
make[3]: Entering directory '/home/ipedrosa/fedpkg/shadow-utils/shadow-4.14.0/man/da'
if grep -q SHADOW-CONFIG-HERE ../gshadow.5.xml ; then \
    sed -e 's/^<!-- SHADOW-CONFIG-HERE -->/<!ENTITY % config SYSTEM "config.xml">%config;/' ../gshadow.5.xml > gshadow.5.xml; \
else \
    sed -e 's/^\(<!DOCTYPE .*docbookx.dtd"\)>/\1 [<!ENTITY % config SYSTEM "config.xml">%config;]>/' ../gshadow.5.xml > gshadow.5.xml; \
fi
itstool -i ../its.rules -d -l da -m messages.mo -o . gshadow.5.xml
Traceback (most recent call last):
  File "/usr/bin/itstool", line 1645, in <module>
    doc.apply_its_file(itsfile, userparams=userparams)
  File "/usr/bin/itstool", line 789, in apply_its_file
    doc = libxml2.parseFile(filename)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/libxml2.py", line 1362, in parseFile
    if ret is None:raise parserError('xmlParseFile() failed')
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
libxml2.parserError: xmlParseFile() failed
make[3]: *** [Makefile:706: gshadow.5.xml] Error 1
make[3]: Leaving directory '/home/ipedrosa/fedpkg/shadow-utils/shadow-4.14.0/man/da'
make[3]: Entering directory '/home/ipedrosa/fedpkg/shadow-utils/shadow-4.14.0/man/da'
if grep -q SHADOW-CONFIG-HERE ../logoutd.8.xml ; then \
    sed -e 's/^<!-- SHADOW-CONFIG-HERE -->/<!ENTITY % config SYSTEM "config.xml">%config;/' ../logoutd.8.xml > logoutd.8.xml; \
else \
    sed -e 's/^\(<!DOCTYPE .*docbookx.dtd"\)>/\1 [<!ENTITY % config SYSTEM "config.xml">%config;]>/' ../logoutd.8.xml > logoutd.8.xml; \
fi
itstool -i ../its.rules -d -l da -m messages.mo -o . logoutd.8.xml
Traceback (most recent call last):
  File "/usr/bin/itstool", line 1645, in <module>
    doc.apply_its_file(itsfile, userparams=userparams)
  File "/usr/bin/itstool", line 789, in apply_its_file
    doc = libxml2.parseFile(filename)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/libxml2.py", line 1362, in parseFile
    if ret is None:raise parserError('xmlParseFile() failed')
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
libxml2.parserError: xmlParseFile() failed
make[3]: *** [Makefile:706: logoutd.8.xml] Error 1
make[3]: Leaving directory '/home/ipedrosa/fedpkg/shadow-utils/shadow-4.14.0/man/da'
make[3]: Entering directory '/home/ipedrosa/fedpkg/shadow-utils/shadow-4.14.0/man/da'
if grep -q SHADOW-CONFIG-HERE ../sg.1.xml ; then \
    sed -e 's/^<!-- SHADOW-CONFIG-HERE -->/<!ENTITY % config SYSTEM "config.xml">%config;/' ../sg.1.xml > sg.1.xml; \
else \
    sed -e 's/^\(<!DOCTYPE .*docbookx.dtd"\)>/\1 [<!ENTITY % config SYSTEM "config.xml">%config;]>/' ../sg.1.xml > sg.1.xml; \
fi
itstool -i ../its.rules -d -l da -m messages.mo -o . sg.1.xml
Traceback (most recent call last):
  File "/usr/bin/itstool", line 1645, in <module>
    doc.apply_its_file(itsfile, userparams=userparams)
  File "/usr/bin/itstool", line 789, in apply_its_file
    doc = libxml2.parseFile(filename)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/libxml2.py", line 1362, in parseFile
    if ret is None:raise parserError('xmlParseFile() failed')
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
libxml2.parserError: xmlParseFile() failed
make[3]: *** [Makefile:706: sg.1.xml] Error 1
make[3]: Leaving directory '/home/ipedrosa/fedpkg/shadow-utils/shadow-4.14.0/man/da'
make[3]: Entering directory '/home/ipedrosa/fedpkg/shadow-utils/shadow-4.14.0/man/da'
if grep -q SHADOW-CONFIG-HERE ../groups.1.xml ; then \
    sed -e 's/^<!-- SHADOW-CONFIG-HERE -->/<!ENTITY % config SYSTEM "config.xml">%config;/' ../groups.1.xml > groups.1.xml; \
else \
    sed -e 's/^\(<!DOCTYPE .*docbookx.dtd"\)>/\1 [<!ENTITY % config SYSTEM "config.xml">%config;]>/' ../groups.1.xml > groups.1.xml; \
fi
itstool -i ../its.rules -d -l da -m messages.mo -o . groups.1.xml
Traceback (most recent call last):
  File "/usr/bin/itstool", line 1645, in <module>
    doc.apply_its_file(itsfile, userparams=userparams)
  File "/usr/bin/itstool", line 789, in apply_its_file
    doc = libxml2.parseFile(filename)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/libxml2.py", line 1362, in parseFile
    if ret is None:raise parserError('xmlParseFile() failed')
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
libxml2.parserError: xmlParseFile() failed
make[3]: *** [Makefile:706: groups.1.xml] Error 1
make[3]: Leaving directory '/home/ipedrosa/fedpkg/shadow-utils/shadow-4.14.0/man/da'
make[3]: Entering directory '/home/ipedrosa/fedpkg/shadow-utils/shadow-4.14.0/man/da'
if grep -q SHADOW-CONFIG-HERE ../newgrp.1.xml ; then \
    sed -e 's/^<!-- SHADOW-CONFIG-HERE -->/<!ENTITY % config SYSTEM "config.xml">%config;/' ../newgrp.1.xml > newgrp.1.xml; \
else \
    sed -e 's/^\(<!DOCTYPE .*docbookx.dtd"\)>/\1 [<!ENTITY % config SYSTEM "config.xml">%config;]>/' ../newgrp.1.xml > newgrp.1.xml; \
fi
itstool -i ../its.rules -d -l da -m messages.mo -o . newgrp.1.xml
Traceback (most recent call last):
  File "/usr/bin/itstool", line 1645, in <module>
    doc.apply_its_file(itsfile, userparams=userparams)
  File "/usr/bin/itstool", line 789, in apply_its_file
    doc = libxml2.parseFile(filename)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/libxml2.py", line 1362, in parseFile
    if ret is None:raise parserError('xmlParseFile() failed')
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
libxml2.parserError: xmlParseFile() failed
make[3]: *** [Makefile:706: newgrp.1.xml] Error 1
make[3]: Leaving directory '/home/ipedrosa/fedpkg/shadow-utils/shadow-4.14.0/man/da'
make[3]: Entering directory '/home/ipedrosa/fedpkg/shadow-utils/shadow-4.14.0/man/da'
if grep -q SHADOW-CONFIG-HERE ../nologin.8.xml ; then \
    sed -e 's/^<!-- SHADOW-CONFIG-HERE -->/<!ENTITY % config SYSTEM "config.xml">%config;/' ../nologin.8.xml > nologin.8.xml; \
else \
    sed -e 's/^\(<!DOCTYPE .*docbookx.dtd"\)>/\1 [<!ENTITY % config SYSTEM "config.xml">%config;]>/' ../nologin.8.xml > nologin.8.xml; \
fi
itstool -i ../its.rules -d -l da -m messages.mo -o . nologin.8.xml
Traceback (most recent call last):
  File "/usr/bin/itstool", line 1645, in <module>
    doc.apply_its_file(itsfile, userparams=userparams)
  File "/usr/bin/itstool", line 789, in apply_its_file
    doc = libxml2.parseFile(filename)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/libxml2.py", line 1362, in parseFile
    if ret is None:raise parserError('xmlParseFile() failed')
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
libxml2.parserError: xmlParseFile() failed
make[3]: *** [Makefile:706: nologin.8.xml] Error 1
make[3]: Leaving directory '/home/ipedrosa/fedpkg/shadow-utils/shadow-4.14.0/man/da'
rm logoutd.8.xml chfn.1.xml gshadow.5.xml newgrp.1.xml groupdel.8.xml sg.1.xml nologin.8.xml groups.1.xml
make[2]: *** [Makefile:750: all-recursive] Error 1
make[1]: *** [Makefile:462: all-recursive] Error 1
make: *** [Makefile:390: all] Error 2
error: Bad exit status from /var/tmp/rpm-tmp.MkhlVc (%build)

RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.MkhlVc (%build)
```

**Comment by jubalh** [comment]
Re manpages I mentioned in the #shadow IRC channel this morning:
```
08:32 < jubalh> RC2  builds fine for me. We dont use the `--enable-lastlog` but if I'm not mistaken then building with it will result in `make[1]: *** No rule to make target 'man8/lastlog.8', needed by 'all-am'.  Stop.` Maybe someone else could confirm
08:33 < jubalh> Even though I see it here: https://github.com/shadow-maint/shadow/pull/749/files#diff-157d6890f983cdcd5238c1886e529156d2c53e56db57aaa3c864b4ab6de4d7a3L50
```
